config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :question_categories
  resources :questions
  resources :chapters
  resources :topics
  resources :subjects
  # get 'exams/index'

  # devise_for :users
   devise_for :users, :controllers => {:registrations => "users/registrations"}
  get 'welcome/index'
  root 'welcome#index'
  resources :exams do
  	member do
      get 'subjects', to: "subjects#index" 
    end
  end
  	resources :subjects do
		member do
			get 'topics', to: "topics#index" 
		end
    end
    resources :topics do
		member do
		get 'chapters', to: "chapters#index" 
		end
    end
	 resources :chapters do
	 	member do
      get 'questions', to: "questions#index" 
      get 'get_question'
      get 'easy_question'
      get 'medium_question'
      get 'hard_question'
    end
	end
  resources :question_categories do
   member do
      get 'questions', to: "questions#index" 
    end
  end
	 resources :questions do

	end
  resources :correct_answers do
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :chapter
	has_one :answer
	# belongs_to :question_category
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    if params[:id].present?
      # byebug
      @chapter = Chapter.find(params[:id])
      @questions = @chapter.questions
      # @questions = Question.all.where(id: @chapter.id)
    else
      @questions = Question.all
    end 
     @que = Question.all.where(category: "Easy")
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def easy_question
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :category, :chapter_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :Chapter %>
 <%= form.collection_select :chapter_id, Chapter.all,:id,:title, include_blank: true %>
</div>
 <div class="field">
    <%= form.label :Question_category %>
    <%#= form.select :question_category, ['Easy', 'Medium', 'Hard'] %>
    <%= form.select :category, options_for_select([['Easy'], ['Medium'], ['Hard']], :selected => :category) %>


    <%#= form.select(:question_category, ['Easy', 'Medium', 'Hard'], {}, { :class => 'my_style_class' }) %>
 <%#= form.collection_select :question_category_id, QuestionCategory.all.uniq,:id,:title, include_blank: true %>
</div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :question_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<center><h1>Questions</h1></center>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
         <td><%#= link_to "#{question.try(:title)}", questions_chapter_path(question.id) %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
   
</table>

<br>
</div>
<div class="col-md-12">
  <% if current_user.admin?%>
<%= link_to 'New Question', new_question_path, :class => "btn btn-lg btn-success btn"  %><br></div>
<%end%>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%#= link_to 'Easy Question', chapter_easy_question_path %>
<%# if @chapter.id.present?%>
<div class="row">
  <div class="col-md-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/chapters/<%= @chapter.try(:id)%>/easy_question" class= "btn btn-lg btn-success btn">Easy Question</a><br><br></div>
<div class="col-md-4">
<a href="/chapters/<%= @chapter.try(:id)%>/medium_question" class= "btn btn-lg btn-success btn">Medium Question</a><br><br></div>
<div class="col-md-4">
<a href="/chapters/<%= @chapter.try(:id)%>/hard_question" class= "btn btn-lg btn-success btn">Hard Question</a></div>
</div><br><br><br><br>
<%#end%>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>