config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :question_categories
  resources :questions
  resources :chapters
  resources :topics
  resources :subjects
  # get 'exams/index'

  # devise_for :users
   devise_for :users, :controllers => {:registrations => "users/registrations"}
  get 'welcome/index'
  root 'welcome#index'
  resources :exams do
  	member do
      get 'subjects', to: "subjects#index" 
    end
  end
  	resources :subjects do
		member do
			get 'topics', to: "topics#index" 
		end
    end
    resources :topics do
		member do
		get 'chapters', to: "chapters#index" 
		end
    end
	 resources :chapters do
	 	member do
      get 'questions', to: "questions#index" 
      get 'get_question'
      get 'easy_question'
      get 'medium_question'
      get 'hard_question'
    end
	end
  resources :question_categories do
   member do
      get 'questions', to: "questions#index" 
    end
  end
	 resources :questions do

	end
  resources :correct_answers do
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
	has_many :questions
	belongs_to :topic
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
	has_many :subjects
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :chapter
	has_one :answer
	# belongs_to :question_category
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
	has_many :questions
	# belongs_to :chapter
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :exam
	has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :subject
	has_many :chapters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :option1, :option2, :option3, :option4, :check1, :check2, :check3, :check4, :skip)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.fetch(:exam, {})
      params.require(:exam).permit(:title)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
      # byebug
    if params[:id].present?
      @subject = Subject.find(params[:id])
      @topics = @subject.topics
    else
    @topics = Topic.all
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :subject_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/correct_answer_helper.rb
module CorrectAnswerHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :Questions %>
 <%= form.collection_select :question_id, Question.all,:id,:title, include_blank: true %>
</div>

  <!-- <div class="field"> -->
    <%#= form.label :question_id %>
    <%#= form.number_field :question_id, id: :answer_question_id %>
  <!-- </div> -->

  <div class="field">
    <%= form.label :option1 %>
    <%= form.text_field :option1, id: :answer_option1 %>
  </div>

  <div class="field">
    <%= form.label :option2 %>
    <%= form.text_field :option2, id: :answer_option2 %>
  </div>

  <div class="field">
    <%= form.label :option3 %>
    <%= form.text_field :option3, id: :answer_option3 %>
  </div>

  <div class="field">
    <%= form.label :option4 %>
    <%= form.text_field :option4, id: :answer_option4 %>
  </div>

  <div class="field">
    <%= form.label :check1 %>
    <%= form.check_box :check1, id: :answer_check1 %>
  </div>

  <div class="field">
    <%= form.label :check2 %>
    <%= form.check_box :check2, id: :answer_check2 %>
  </div>

  <div class="field">
    <%= form.label :check3 %>
    <%= form.check_box :check3, id: :answer_check3 %>
  </div>

  <div class="field">
    <%= form.label :check4 %>
    <%= form.check_box :check4, id: :answer_check4 %>
  </div>

  <div class="field">
    <%= form.label :skip %>
    <%= form.check_box :skip, id: :answer_skip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Option4</th>
      <th>Check1</th>
      <th>Check2</th>
      <th>Check3</th>
      <th>Check4</th>
      <th>Skip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.option1 %></td>
        <td><%= answer.option2 %></td>
        <td><%= answer.option3 %></td>
        <td><%= answer.option4 %></td>
        <td><%= answer.check1 %></td>
        <td><%= answer.check2 %></td>
        <td><%= answer.check3 %></td>
        <td><%= answer.check4 %></td>
        <td><%= answer.skip %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.admin?%>
<%= link_to 'New Answer', new_answer_path %>
<%end%>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @answer.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @answer.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @answer.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @answer.option4 %>
</p>

<p>
  <strong>Check1:</strong>
  <%= @answer.check1 %>
</p>

<p>
  <strong>Check2:</strong>
  <%= @answer.check2 %>
</p>

<p>
  <strong>Check3:</strong>
  <%= @answer.check3 %>
</p>

<p>
  <strong>Check4:</strong>
  <%= @answer.check4 %>
</p>

<p>
  <strong>Skip:</strong>
  <%= @answer.skip %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= form.label :Subject %>
 <%= form.collection_select :subject_id, Subject.all,:id,:title, include_blank: true %>
</div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :topic_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<center><h1>Topics</h1></center>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <!-- <td><a href="/chapters"><%= topic.title %></a></td> -->
         <td><%= link_to "#{topic.try(:title)}", chapters_topic_path(topic.id) %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% if current_user.admin?%>
<%= link_to 'New Topic', new_topic_path %>
<%end%>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>