config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :question_categories
  resources :questions
  resources :chapters
  resources :topics
  resources :subjects
  # get 'exams/index'

  # devise_for :users
   devise_for :users, :controllers => {:registrations => "users/registrations"}
  get 'welcome/index'
  root 'welcome#index'
  resources :exams do
  	member do
      get 'subjects', to: "subjects#index" 
    end
  end
  	resources :subjects do
		member do
			get 'topics', to: "topics#index" 
		end
    end
    resources :topics do
		member do
		get 'chapters', to: "chapters#index" 
		end
    end
	 resources :chapters do
	 	member do
      get 'questions', to: "questions#index" 
      get 'get_question'
      get 'easy_question'
      get 'medium_question'
      get 'hard_question'
    end
	end
  resources :question_categories do
   member do
      get 'questions', to: "questions#index" 
    end
  end
	 resources :questions do

	end
  resources :correct_answers do
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
	has_many :questions
	belongs_to :topic
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    if params[:id].present?
      @topic = Topic.find(params[:id])
      @chapters = @topic.try(:chapters)
    else
     @chapters = Chapter.all
    end
   
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def easy_question
    @chapter = Chapter.find(params[:id])
    @que = Question.all.where(category: "Easy").where(chapter_id: @chapter.id).paginate(:page => params[:page], :per_page => 1) 
  end
  def medium_question
    # byebug
    @chapter = Chapter.find(params[:id])
    @ques = @chapter.questions.where(category: "Medium").where(chapter_id: @chapter.id)
    @que = @ques.find(params[:medium_question]) 
    # @que = Question.all.where(category: "Medium").where(chapter_id: @chapter.id).paginate(:page => params[:page], :per_page => 1) 
  end
  def hard_question
    @chapter = Chapter.find(params[:id])
    @que = Question.all.where(category: "Hard").where(chapter_id: @chapter.id).paginate(:page => params[:page], :per_page => 1) 
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :topic_id)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_with(model: chapter, local: true) do |form| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= form.label :Topics %>
 <%= form.collection_select :topic_id, Topic.all,:id,:title, include_blank: true %>
</div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :chapter_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chapters/easy_question.html.erb
<%= form_for :correct_answer, :url => correct_answers_path, html: {id: "question_submit"}, class: "form-horizontal" do |c| %>
<div class="well bs-component">
   <div class="container-fluid">
      <% @que.each do |question| %>
      <tr>
         <h1>
            <td><%= question.title %></td>
         </h1>
         <br>
         <div class="form-group">
            <div class="checkbox">
               <label>
               <% if question.answer.try(:check1) == true %>
               <%= c.check_box :correct_answer,{}, true%><%= question.answer.try(:option1) %>
               <br>
               <%else%>
               <%= c.check_box :correct_answer,{}, false%><%= question.answer.try(:option1) %><br>
               <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check2) == true %>
                  <td><%= c.check_box :correct_answer1 ,{}, true%><%= question.answer.try(:option2) %></td>
                  <br>
                  <%else%>
                  <td><%= c.check_box :correct_answer1 ,{}, false%><%= question.answer.try(:option2) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check3) == true %>
                  <td><%= c.check_box :correct_answer2 ,{}, true%><%= question.answer.try(:option3) %></td>
                  <br>   
                  <%else%>   
                  <td><%= c.check_box :correct_answer2 ,{}, false%><%= question.answer.try(:option3) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check4) == true %>                          
                  <td><%= c.check_box :correct_answer3 ,{}, true%><%= question.answer.try(:option4) %></td>
                  <br>
                  <%else%>
                  <td><%= c.check_box :correct_answer3 ,{}, false%><%= question.answer.try(:option4) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <td><%= c.hidden_field :user_id, :value => current_user.id %></td>
         <%#byebug%>
         <%# if  will_paginate @que, id: "skip" %>
         <td><%= c.hidden_field :skip_question, id: "skiped_question"%></td>
         <%#else%>
         <td><%#= c.hidden_field :skip_question, :value => false%></td>
         <%#end%>
         <td><%= c.hidden_field :question_id, :value => question.try(:id) %></td>
         <td><%= c.hidden_field :answer_id, :value => question.answer.try(:id) %></td>
      </tr>
      <%end%>
   </div>
</div>
<center>
   <% if @que.count == params[:page].to_i  %>
   <%= c.submit "Submit", :name => "submit_form", :value =>"submit", type: "submit", class: "btn btn-lg btn-success btn"%>
   <%else%>
   <%= will_paginate @que,:page_links => false, :previous_label => '', :next_label => 'Skip', id: "skip", class: "btn btn-lg btn-success btn", :name => "skip", :value =>"true" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   <%= will_paginate @que, :page_links => false, :previous_label => '', id: "next", class: "btn btn-lg btn-success btn"%>
   <%end%>
</center>
<% end %>
<script type="text/javascript">
   $('#next').on('click', function () {
     // console.log('hiiiiiiiiiiiiiiiiiii')
     $('#question_submit').submit();
   })
   $('#skip').on('click', function () {
     $('#skiped_question').val("true");
     $('#question_submit').submit();
   })
   
</script>
<style type="text/css">
   .container-fluid {
   margin-right: auto;
   margin-left: auto;
   padding-left: 15px;
   padding-right: 15px;
   }
   .well {
   margin-left: 200px;
   margin-right: 200px;
   margin-top: 143px;
   min-height: 20px;
   padding: 19px;
   margin-bottom: 20px;
   background-color: #D5DBDB;
   border: 1px solid transparent;
   border-radius: 4px;
   -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   }
   .well {
   -webkit-box-shadow: none;
   box-shadow: none;
   }
</style>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/hard_question.html.erb
<%= form_for :correct_answer, :url => correct_answers_path, html: {id: "question_submit"}, class: "form-horizontal" do |c| %>
<div class="well bs-component">
   <div class="container-fluid">
      <% @que.each do |question| %>
      <tr>
         <h1>
            <td><%= question.title %></td>
         </h1>
         <br>
         <div class="form-group">
            <div class="checkbox">
               <label>
               <% if question.answer.try(:check1) == true %>
               <%= c.check_box :correct_answer,{}, true%><%= question.answer.try(:option1) %>
               <br>
               <%else%>
               <%= c.check_box :correct_answer,{}, false%><%= question.answer.try(:option1) %><br>
               <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check2) == true %>
                  <td><%= c.check_box :correct_answer1 ,{}, true%><%= question.answer.try(:option2) %></td>
                  <br>
                  <%else%>
                  <td><%= c.check_box :correct_answer1 ,{}, false%><%= question.answer.try(:option2) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check3) == true %>
                  <td><%= c.check_box :correct_answer2 ,{}, true%><%= question.answer.try(:option3) %></td>
                  <br>   
                  <%else%>   
                  <td><%= c.check_box :correct_answer2 ,{}, false%><%= question.answer.try(:option3) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check4) == true %>                          
                  <td><%= c.check_box :correct_answer3 ,{}, true%><%= question.answer.try(:option4) %></td>
                  <br>
                  <%else%>
                  <td><%= c.check_box :correct_answer3 ,{}, false%><%= question.answer.try(:option4) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <td><%= c.hidden_field :user_id, :value => current_user.id %></td>
         <%#byebug%>
         <% if  will_paginate @que, id: "skip" %>
         <td><%= c.hidden_field :skip_question, :value => true%></td>
         <%else%>
         <td><%= c.hidden_field :skip_question, :value => false%></td>
         <%end%>
         <td><%= c.hidden_field :question_id, :value => question.try(:id) %></td>
         <td><%= c.hidden_field :answer_id, :value => question.answer.try(:id) %></td>
      </tr>
      <%end%>
   </div>
</div>
<center>
   <% if @que.count == params[:page].to_i  %>
   <%= c.submit "Submit", :name => "submit_form", :value =>"submit", type: "submit", class: "btn btn-lg btn-success btn"%>
   <%else%>
   <%= will_paginate @que,:page_links => false, :previous_label => '', :next_label => 'Skip', id: "skip", class: "btn btn-lg btn-success btn" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   <%= will_paginate @que, :page_links => false, :previous_label => '', id: "next", class: "btn btn-lg btn-success btn"%>
   <%end%>
</center>
<% end %>
<script type="text/javascript">
   $('#next').on('click', function () {
     // console.log('hiiiiiiiiiiiiiiiiiii')
     $('#question_submit').submit();
   })
   $('#skip').on('click', function () {
     $('#question_submit').submit();
   })
   
</script>
<style type="text/css">
   .container-fluid {
   margin-right: auto;
   margin-left: auto;
   padding-left: 15px;
   padding-right: 15px;
   }
   .well {
   margin-left: 200px;
   margin-right: 200px;
   margin-top: 143px;
   min-height: 20px;
   padding: 19px;
   margin-bottom: 20px;
   background-color: #D5DBDB;
   border: 1px solid transparent;
   border-radius: 4px;
   -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   }
   .well {
   -webkit-box-shadow: none;
   box-shadow: none;
   }
</style>

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<center><h1>Chapters</h1></center>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <!-- <td><a href="/questions"><%#= chapter.try(:title) %></a></td> -->
          <td><%= link_to "#{chapter.try(:title)}", questions_chapter_path(chapter.id) %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% if current_user.admin?%>
<%= link_to 'New Chapter', new_chapter_path %>
<%end%>

app/views/chapters/medium_question.html.erb
<%= form_for :correct_answer, :url => correct_answers_path, html: {id: "question_submit"}, class: "form-horizontal" do |c| %>
<div class="well bs-component">
   <div class="container-fluid">
      <% @que.each do |question| %>
      <tr>
         <h1>
            <td><%= question.title %></td>
         </h1>
         <br>
         <div class="form-group">
            <div class="checkbox">
               <label>
               <% if question.answer.try(:check1) == true %>
               <%= c.check_box :correct_answer,{}, true%><%= question.answer.try(:option1) %>
               <br>
               <%else%>
               <%= c.check_box :correct_answer,{}, false%><%= question.answer.try(:option1) %><br>
               <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check2) == true %>
                  <td><%= c.check_box :correct_answer1 ,{}, true%><%= question.answer.try(:option2) %></td>
                  <br>
                  <%else%>
                  <td><%= c.check_box :correct_answer1 ,{}, false%><%= question.answer.try(:option2) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check3) == true %>
                  <td><%= c.check_box :correct_answer2 ,{}, true%><%= question.answer.try(:option3) %></td>
                  <br>   
                  <%else%>   
                  <td><%= c.check_box :correct_answer2 ,{}, false%><%= question.answer.try(:option3) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <div class="form-group">
            <div class="checkbox">
               <label>
                  <% if question.answer.try(:check4) == true %>                          
                  <td><%= c.check_box :correct_answer3 ,{}, true%><%= question.answer.try(:option4) %></td>
                  <br>
                  <%else%>
                  <td><%= c.check_box :correct_answer3 ,{}, false%><%= question.answer.try(:option4) %></td>
                  <br>
                  <%end%>
               </label>
            </div>
         </div>
         <td><%= c.hidden_field :user_id, :value => current_user.id %></td>
         <%#byebug%>
         <% if  will_paginate @que, id: "skip" %>
         <td><%= c.hidden_field :skip_question, :value => true%></td>
         <%else%>
         <td><%= c.hidden_field :skip_question, :value => false%></td>
         <%end%>
         <td><%= c.hidden_field :question_id, :value => question.try(:id) %></td>
         <td><%= c.hidden_field :answer_id, :value => question.answer.try(:id) %></td>
      </tr>
      <%end%>
   </div>
</div>
<center>
   <% if @que.count == params[:page].to_i  %>
   <%= c.submit "Submit", :name => "submit_form", :value =>"submit", type: "submit", class: "btn btn-lg btn-success btn"%>
   <%else%>
   <%= will_paginate @que,:page_links => false, :previous_label => '', :next_label => 'Skip', id: "skip", class: "btn btn-lg btn-success btn" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   <%= will_paginate @que, :page_links => false, :previous_label => '', id: "next", class: "btn btn-lg btn-success btn"%>
   <%end%>
</center>
<% end %>
<script type="text/javascript">
   $('#next').on('click', function () {
     // console.log('hiiiiiiiiiiiiiiiiiii')
     $('#question_submit').submit();
   })
   $('#skip').on('click', function () {
     $('#question_submit').submit();
   })
   
</script>
<style type="text/css">
   .container-fluid {
   margin-right: auto;
   margin-left: auto;
   padding-left: 15px;
   padding-right: 15px;
   }
   .well {
   margin-left: 200px;
   margin-right: 200px;
   margin-top: 143px;
   min-height: 20px;
   padding: 19px;
   margin-bottom: 20px;
   background-color: #D5DBDB;
   border: 1px solid transparent;
   border-radius: 4px;
   -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   }
   .well {
   -webkit-box-shadow: none;
   box-shadow: none;
   }
</style>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>