config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :question_categories
  resources :questions
  resources :chapters
  resources :topics
  resources :subjects
  # get 'exams/index'

  # devise_for :users
   devise_for :users, :controllers => {:registrations => "users/registrations"}
  get 'welcome/index'
  root 'welcome#index'
  resources :exams do
  	member do
      get 'subjects', to: "subjects#index" 
    end
  end
  	resources :subjects do
		member do
			get 'topics', to: "topics#index" 
		end
    end
    resources :topics do
		member do
		get 'chapters', to: "chapters#index" 
		end
    end
	 resources :chapters do
	 	member do
      get 'questions', to: "questions#index" 
      get 'get_question'
      get 'easy_question'
      get 'medium_question'
      get 'hard_question'
    end
	end
  resources :question_categories do
   member do
      get 'questions', to: "questions#index" 
    end
  end
	 resources :questions do

	end
  resources :correct_answers do
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
	has_many :questions
	belongs_to :topic
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
	has_many :subjects
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :chapter
	has_one :answer
	# belongs_to :question_category
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
	has_many :questions
	# belongs_to :chapter
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :exam
	has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :subject
	has_many :chapters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :option1, :option2, :option3, :option4, :check1, :check2, :check3, :check4, :skip)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.fetch(:exam, {})
      params.require(:exam).permit(:title)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
      # byebug
    if params[:id].present?
      @subject = Subject.find(params[:id])
      @topics = @subject.topics
    else
    @topics = Topic.all
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :subject_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/correct_answer_helper.rb
module CorrectAnswerHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
<div class="well bs-component">
   <div class="container-fluid">
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%#= form.label :Subject %>
 <%#= form.collection_select :subject_id, Subject.all,:id,:title, include_blank: true %>
</div>
<div class="form-group">
<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :exam_title, class: 'form-control', style: ' width: 40%; '  %>
  </div>
</div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>

</div>
</div>

<% end %>
<style type="text/css">
   .container-fluid {
   margin-right: auto;
   margin-left: auto;
   padding-left: 15px;
   padding-right: 15px;
   }
   .well {
   margin-left: 400px;
   margin-right: 400px;
   margin-top: 143px;
   min-height: 20px;
   padding: 19px;
   margin-bottom: 20px;
   background-color: #D5DBDB;
   border: 1px solid transparent;
   border-radius: 4px;
   -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
   background-image: url('https://images.unsplash.com/photo-1534448177492-6d698f12a59a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80');
   }
   .well {
   -webkit-box-shadow: none;
   box-shadow: none;
   }
</style>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<center><h1>Exams</h1></center>

<table class="table table-striped">
  <thead>
    <tr>
       <th>Title</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
      	<td><%= link_to "#{exam.try(:title)}", subjects_exam_path(exam.id) %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%#= link_to 'New Exam', new_exam_path%>
<% if current_user.admin?%>
<a href="/exams/new" class="btn btn-success" role="button">New Exam</a>
<%end%>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @exam.title %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>